version: "3.8"

networks:
  inside:
    external: false


services:
  webserver:
    build: .
    container_name: "apache"
    hostname: "apache"
    ports:
      - 80
      - 443
    volumes:
      - ./volume/html:/usr/share/nginx/html
    restart: always
